function d(a){function b(b){return a.next(b)}function c(b){return a["throw"](b)}return new Promise(function(f,g){function k(a){a.done?f(a.value):Promise.resolve(a.value).then(b,c).then(k,g)}k(a.next())})}
var e="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function p(){p=function(){};h.Symbol||(h.Symbol=q)}var r=0;function q(a){return"jscomp_symbol_"+(a||"")+r++}
function t(){p();var a=h.Symbol.iterator;a||(a=h.Symbol.iterator=h.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&e(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return u(this)}});t=function(){}}function u(a){var b=0;return w(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function w(a){t();a={next:a};a[h.Symbol.iterator]=function(){return this};return a}function y(a){t();var b=a[Symbol.iterator];return b?b.call(a):u(a)}
for(var z=h,A=["Promise"],B=0;B<A.length-1;B++){var C=A[B];C in z||(z[C]={});z=z[C]}
var D=A[A.length-1],E=z[D],F=function(){function a(a){this.b=0;this.h=void 0;this.a=[];var b=this.f();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}}function b(){this.a=null}if(E)return E;b.prototype.b=function(a){this.a||(this.a=[],this.f());this.a.push(a)};b.prototype.f=function(){var a=this;this.c(function(){a.h()})};var c=h.setTimeout;b.prototype.c=function(a){c(a,0)};b.prototype.h=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];
try{c()}catch(m){this.g(m)}}}this.a=null};b.prototype.g=function(a){this.c(function(){throw a;})};a.prototype.f=function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;return{resolve:a(this.o),reject:a(this.g)}};a.prototype.o=function(b){if(b===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.s(b);else{var g;a:switch(typeof b){case "object":g=null!=b;break a;case "function":g=!0;break a;default:g=!1}g?this.m(b):this.i(b)}};a.prototype.m=
function(a){var b=void 0;try{b=a.then}catch(l){this.g(l);return}"function"==typeof b?this.u(b,a):this.i(a)};a.prototype.g=function(a){this.j(2,a)};a.prototype.i=function(a){this.j(1,a)};a.prototype.j=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.b);this.b=a;this.h=b;this.l()};a.prototype.l=function(){if(this.a){for(var a=this.a,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.a=null}};var f=new b;a.prototype.s=function(a){var b=this.f();a.c(b.resolve,
b.reject)};a.prototype.u=function(a,b){var c=this.f();try{a.call(b,c.resolve,c.reject)}catch(m){c.reject(m)}};a.prototype.then=function(b,c){function f(a,b){return"function"==typeof a?function(b){try{g(a(b))}catch(v){k(v)}}:b}var g,k,n=new a(function(a,b){g=a;k=b});this.c(f(b,g),f(c,k));return n};a.prototype["catch"]=function(a){return this.then(void 0,a)};a.prototype.c=function(a,b){function c(){switch(g.b){case 1:a(g.h);break;case 2:b(g.h);break;default:throw Error("Unexpected state: "+g.b);}}var g=
this;this.a?this.a.push(function(){f.b(c)}):f.b(c)};a.resolve=function(b){return b instanceof a?b:new a(function(a){a(b)})};a.reject=function(b){return new a(function(a,c){c(b)})};a.b=function(b){return new a(function(c,f){for(var g=y(b),k=g.next();!k.done;k=g.next())a.resolve(k.value).c(c,f)})};a.a=function(b){var c=y(b),f=c.next();return f.done?a.resolve([]):new a(function(b,g){function k(a){return function(c){l[a]=c;m--;m||b(l)}}var l=[],m=0;do l.push(void 0),m++,a.resolve(f.value).c(k(l.length-
1),g),f=c.next();while(!f.done)})};a.$jscomp$new$AsyncExecutor=function(){return new b};return a}();F!=E&&null!=F&&e(z,D,{configurable:!0,writable:!0,value:F});var G=new TextDecoder("utf-8"),H=null,I={},J={},K=[],L=null,O=[],P=[null];function Q(a){if(O.length){var b=O.shift();P[b]=a;return b}P.push(a);return P.length-1}function R(a){delete P[a];O.push(a)}J.glActiveTexture=function(a){L.activeTexture(a)};J.glAttachShader=function(a,b){L.attachShader(P[a],P[b])};
J.glBindBuffer=function(a,b){L.bindBuffer(a,P[b])};J.glBindTexture=function(a,b){L.bindTexture(a,P[b])};J.glBindVertexArray=function(a){L.bindVertexArray(P[a])};J.glBufferData=function(a,b,c,f){L.bufferData(a,H.subarray(b,b+f),c)};J.glClearBuffer=function(a,b,c,f,g,k){L.clearBufferfv(a,b,new Float32Array([c,f,g,k]))};J.glCompileShader=function(a){L.compileShader(P[a])};J.glCreateBuffer=function(){var a=L.createBuffer();return Q(a)};J.glCreateProgram=function(){return Q(L.createProgram())};
J.glCreateShader=function(a){return Q(L.createShader(a))};J.glCreateVertexArray=function(){var a=L.createVertexArray();return Q(a)};J.glCullFace=function(a){L.cullFace(a)};J.glDeleteBuffer=function(a){L.deleteBuffer(P[a]);R(a)};J.glDeleteProgram=function(a){L.deleteProgram(P[a]);R(a)};J.glDeleteShader=function(a){L.deleteShader(P[a]);R(a)};J.glDeleteVertexArray=function(a){L.deleteVertexArray(P[a]);R(a)};J.glDetachShader=function(a,b){L.detachShader(P[a],P[b])};J.glDisable=function(a){L.disable(a)};
J.glDrawElements=function(a,b,c,f){L.drawElements(a,b,c,f)};J.glEnable=function(a){L.enable(a)};J.glEnableVertexAttribArray=function(a){L.enableVertexAttribArray(a)};J.glCreateTexture=function(){var a=L.createTexture();return Q(a)};J.glGetProgramParameter=function(a,b){return L.getProgramParameter(P[a],b)};J.glGetShaderParameter=function(a,b){return L.getShaderParameter(P[a],b)};J.glGenerateMipmap=function(a){L.generateMipmap(a)};
J.glGetUniformLocation=function(a,b,c){a=P[a];b=G.decode(H.subarray(b,b+c));return Q(L.getUniformLocation(a,b))};J.glLinkProgram=function(a){L.linkProgram(P[a])};J.glShaderSource=function(a,b,c){L.shaderSource(P[a],G.decode(H.subarray(b,b+c)))};J.glTexParameterf=function(a,b,c){L.texParameterf(a,b,c)};J.glTexParameteri=function(a,b,c){L.texParameteri(a,b,c)};J.glTexStorage2D=function(a,b,c,f,g){L.texStorage2D(a,b,c,f,g)};
J.glTexSubImage2D=function(a,b,c,f,g,k,l,m,x,n){L.texSubImage2D(a,b,c,f,g,k,l,m,H.slice(x,x+n))};J.glUniform1i=function(a,b){L.uniform1i(P[a],b)};J.glUniform3fv=function(a,b,c,f){L.uniform3fv(P[a],[b,c,f])};J.glUniformMatrix4fv=function(a,b){L.uniformMatrix4fv(P[a],!1,new Float32Array(H.slice(b,b+64).buffer))};J.glUseProgram=function(a){L.useProgram(P[a])};J.glVertexAttribPointer=function(a,b,c,f,g,k){L.vertexAttribPointer(a,b,c,f,g,k)};J.glViewport=function(a,b,c,f){L.viewport(a,b,c,f)};
J.glutil_printShaderInfoLog=function(a){console.log("Shader log:\n"+L.getShaderInfoLog(P[a]))};J.glutil_printProgramInfoLog=function(a){console.log("Program log:\n"+L.getProgramInfoLog(P[a]))};J.util_buffer_get=function(a,b){var c=K[a];H.subarray(b,b+c.byteLength).set(new Uint8Array(c));return!0};J.date_now=function(){return.001*Date.now()};
function S(){var a=window.devicePixelRatio,b=window.innerWidth,c=window.innerHeight;L.canvas.width=b*a|0;L.canvas.height=c*a|0;I.engine_window_resize(b*a|0,c*a|0);console.log("resize: ["+(b*a|0)+", "+(c*a|0)+"] > ["+(b|0)+", "+(c|0)+"]")}function T(){I.render();window.requestAnimationFrame(T)}function U(a){return new Promise(function(b){fetch(a).then(function(a){a.arrayBuffer().then(function(a){return b(a)})})})}var V=document.createElement("canvas").getContext("2d");
function W(a){return new Promise(function(b,c){var f=new Image;f.src=a;f.onerror=c;f.onload=function(){V.canvas.width=f.width;V.canvas.height=f.height;V.width=f.width;V.height=f.height;V.drawImage(f,0,0);var a=V.getImageData(0,0,f.width,f.height),a=new Uint8Array(a.data.buffer);b(a)}})}
window.onload=function(){return d(function(){function a(a,v){for(;;)switch(b){case 0:M={alpha:!1,depth:!0,stencil:!1,antialias:!0,preserveDrawingBuffer:!1};if(L=document.getElementById("mcanvas").getContext("webgl2",M))L.getExtension("EXT_texture_filter_anisotropic");else throw console.log("Your browser does not support WebGL 2"),"Your browser does not support WebGL 2";K[0]=U("binary");K[1]=U("model.buf");K[2]=W("textures/diffuse.png");K[3]=W("textures/normal.png");n=0;case 1:if(!(n<K.length)){b=
3;break}x=K;m=n;b=4;return{value:K[n],done:!1};case 4:if(void 0===v){b=5;break}b=-1;throw v;case 5:l=a,x[m]=l;case 2:n++;b=1;break;case 3:return V=null,k=K[0],J.memory=new WebAssembly.Memory({initial:32}),H=new Uint8Array(J.memory.buffer),b=6,{value:WebAssembly.instantiate(k,{env:J}),done:!1};case 6:if(void 0===v){b=7;break}b=-1;throw v;case 7:f=g=a;c=f.instance;I=c.exports;S();window.addEventListener("resize",S);if(!I.init())throw console.log("Engine initialization failed"),"Engine initialization failed";
T();b=-1;default:return{value:void 0,done:!0}}}var b=0,c,f,g,k,l,m,x,n,M,N={next:function(b){return a(b,void 0)},"throw":function(b){return a(void 0,b)},"return":function(){throw Error("Not yet implemented");}};t();N[Symbol.iterator]=function(){return this};return N}())};
